### ISSUE TITLE
requirement on pytz

### ISSUE THREAD

**Issue by laszewsk** [codecov/timestring#25]
can the requirement on payt. be changed. we are now having issues as some modules require much newer pytz libraries, but this library requires an exact version :(

**Comment by stevepeak** [comment]
No problem! Thanks for the feedback.

**Comment by laszewsk** [comment]
Great, we saw your fix. Ian not yet sure if this solves it. We actually use the module on pypi but that still has the ==. We will now try the pip install via your repo. We use your module in cloud mesh, which provides the ability to use VMs in AWS, OpenStack, Azure, Eucalyptus, ... . We have integrated it into a command line tool so users can specify conveniently dates. We like it a lot.

**Comment by stevepeak** [comment]
I did not deploy this version yet. I'm hoping to get to this shortly. 

Thanks for helping out and I'm glad to see this tool used! Your feedback and PR's are very welcome!

**Comment by MinchinWeb** [comment]
Can the version with this update be released to the wild? That would be much appreciated!

**Comment by laszewsk** [comment]
As user of pytz we use for quite some time a fork as we were no sure if the issues were resolved in this version. Once we know we switch back. 

https://github.com/cloudmesh/timestring
https://pypi.python.org/pypi/cloudmesh_timestring

**Comment by MinchinWeb** [comment]
Thank you @laszewsk !

**Comment by stevepeak** [comment]
@laszewsk would you like to make a PR with these changes: https://github.com/cloudmesh/timestring/compare/25c0ae2c8aa69e0c9628e0a92d9c7f1210205cb1...master

Thank you!

**Comment by stevepeak** [comment]
ps @laszewsk @MinchinWeb I'm looking for more core contributors to this project interested?

**Comment by MinchinWeb** [comment]
@stevepeak I created PR #37 that covers off the changes.

@laszewsk, was there some reason you bumped the minimum version of pytz to 2015.2?

**Comment by MinchinWeb** [comment]
P.S. @stevepeak: What did you have in mind? I would probably be interested, depending on the details.

**Comment by laszewsk** [comment]
The reason for bumping the version is that the earlier versions introduce an incompatibility with openstack. 
We simply bumped up the version and it worked. So there was no development actually goint on. However we needed that version accessible via pypi, so we were forced to create our own requirements and upload it under a different name to pypi. This way we can use it in cloudmesh client.

**Comment by thomasrockhu** [comment]
This should be resolved via the release of `1.6.3` and above!
