### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by asteriogonzalez** [codecov/timestring#35]
Thanks Steve for your library.

I sow a typo mistake in:

test.py, line 229

for x, day in enumerate(('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'Satruday', 'sunday')):

Should be  'Satruday'  -> 'saturday' ?

**Comment by thomasrockhu** [comment]
Fixed via https://github.com/codecov/timestring/commit/773c2058d4a5ef619baeb1556a917ea2f4838076#diff-61d51a325171d97c8a56e59ea525339b
